blank_issues_enabled: true
contact_links:
  - name: Wiki
    url: https://readyyourshovels.teamhollow.net
    about: A detailed summary of Ready Your Shovels's features
  - name: Features Roadmap (Trello)
    url: https://trello.com/b/krhbFb8Y
    about: A list of features and plans for the future - check here if you're making a feature request!
